# Generated by Django 6.0 on 2026-04-08 08:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('channel_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID канала')),
                ('title', models.TextField(verbose_name='Заголовок')),
                ('link', models.TextField(verbose_name='Ссылка')),
                ('short_title', models.CharField(default='', max_length=32, verbose_name='Короткий заголовок')),
                ('html_desc', models.TextField(verbose_name='Описание в HTML')),
            ],
            options={
                'verbose_name': 'Канал',
                'verbose_name_plural': 'Каналы',
                'db_table': 'channels',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('sort', models.IntegerField(verbose_name='Порядок сортировки')),
                ('hide_content', models.BooleanField(default=False, verbose_name='Скрыть содержимое')),
                ('short_title', models.CharField(max_length=64, verbose_name='Короткий заголовок')),
                ('html_desc', models.TextField(verbose_name='Описание в HTML')),
                ('parent', models.BigIntegerField(verbose_name='ID родительской группы')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'db_table': 'groups',
            },
        ),
        migrations.CreateModel(
            name='GroupChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.ForeignKey(db_column='channel_id', on_delete=django.db.models.deletion.CASCADE, to='core.channel')),
                ('group', models.ForeignKey(db_column='group_id', on_delete=django.db.models.deletion.CASCADE, to='core.group')),
            ],
            options={
                'verbose_name': 'Связь группы и канала',
                'verbose_name_plural': 'Связи групп и каналов',
                'db_table': 'group_channels',
                'unique_together': {('group', 'channel')},
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(verbose_name='Заголовок новости')),
                ('link', models.TextField(verbose_name='Ссылка на новость')),
                ('pubDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('description', models.TextField(verbose_name='Текст новости')),
                ('channel', models.ForeignKey(db_column='channel_id', on_delete=django.db.models.deletion.CASCADE, to='core.channel')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'db_table': 'items',
                'indexes': [models.Index(fields=['pubDate'], name='items_pubDate_fb37a9_idx'), models.Index(fields=['channel'], name='items_channel_80ee5b_idx')],
            },
        ),
    ]
