# Generated by Django 6.0 on 2026-04-13 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_item_pubdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parsed_at', models.DateTimeField(auto_now_add=True, verbose_name='Время парсинга')),
                ('items_found', models.IntegerField(default=0, verbose_name='Найдено новостей')),
                ('items_added', models.IntegerField(default=0, verbose_name='Добавлено новостей')),
                ('error_message', models.TextField(blank=True, verbose_name='Ошибка')),
                ('duration_seconds', models.FloatField(default=0, verbose_name='Длительность (сек)')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.channel', verbose_name='Канал')),
            ],
            options={
                'verbose_name': 'Лог парсинга',
                'verbose_name_plural': 'Логи парсинга',
                'db_table': 'parsing_logs',
                'ordering': ['-parsed_at'],
            },
        ),
    ]
